### ISSUE TITLE
Playerlist update delay?

### ISSUE THREAD

**Issue by CptEagle** [11TStudio/SquadStatsJSPRO#55]
**Describe the bug**
When player joined the server it takes a while by when you see the on the player list 

**Expectedr**
Increase the playerlist on refresh

**Comment by 11TStudio** [comment]
PLAYER_CONNECTED event is fired once the player is logged in the server.cfg logs. Since SQUADJS is not using the RCON event playerConnected (don't even know if that even is a thing since Squad is not really following the default RCON protocols)...

But that might be solved in the later SQUADJS updates, where Squad would fire (at least the same info they log in the logs) in the rcon once player has been connected...

For now this bug/issue is not valid as there is nothing I can do, but add a rcon implementention for this which is out of scope for this project.
